import Image from "next/image";
import "./globals.css";
import type { Metadata } from "next";
import Link from "next/link";
import { AiFillGithub } from "react-icons/ai";
// import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className="bg-green-200 p-4">
          <div className="max-w-[1200px] m-auto flex justify-between items-center">
            <h1 className="text-4xl">💎 sohyun&#39;s blog</h1>
            <nav className="text-xl flex gap-6">
              <Link href={"/"} className="hover:text-white">
                Home
              </Link>
              <Link href={"/about"} className="hover:text-white">
                About
              </Link>
              <Link href={"/posts"} className="hover:text-white">
                Posts
              </Link>
              <Link href={"/contact"} className="hover:text-white">
                Contact
              </Link>
            </nav>
          </div>
        </header>
        <section className="bg-green-100 p-5">
          <div className="flex flex-col gap-2 justify-center items-center">
            <Image
              src="/images/my_image_1.png"
              alt="avatar"
              width={200}
              height={200}
            />
            <h2 className="text-2xl mt-4"> Welcome! To my secret blog 👑</h2>
            <p className="text-xl mb-2"> I&#39;m Frontend developer Sohyun.</p>
            <button className=" text-lg text-white bg-indigo-500 p-2 px-4 rounded-md">
              Contact
            </button>
          </div>
        </section>
        <main className="max-w-[1200px] m-auto p-5">{children}</main>
        <footer className=" text-xl bg-indigo-200 p-8 flex  flex-col items-center gap-2">
          <AiFillGithub />
          <p>Park So Hyun - All rignts reserved</p>
        </footer>
      </body>
    </html>
  );
}
